name: Deploy to AWS using Terraform

on:
  push:
    branches:
      - main   # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main   # Optionally, trigger on pull requests to main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.5  # Specify the Terraform version you want to use

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform configuration
      run: terraform validate

    - name: Apply Terraform plan
      run: terraform apply -auto-approve

    - name: Output instance ID
      run: echo "Instance ID: $(terraform output instance_id)"
